 export const providerList = [
  {
    clinicId: 93422,
    id: 134,
    firstName: "Vinit",
    fullName: "Vinit Lal",
    middleName: " ",
    lastName: "Lal",
    providerType: 1,
  },
  {
    clinicId: 93422,
    id: 135,
    firstName: "Randall",
    fullName: "Randall Gale",
    lastName: "Gale",
    middleName: " Glenn",
    providerType: 1,
  },
  {
    clinicId: 93422,
    id: 136,
    firstName: "Kelsey ",
    fullName: "Kelsey Reekie",
    middleName: " ",
    lastName: "Reekie",
    providerType: 1,
  },
  {
    clinicId: 93422,
    id: 137,
    firstName: "Mesha ",
    fullName: "Mesha Dancer",
    middleName: " ",
    lastName: "Dancer",
    providerType: 1,
  },
  {
    clinicId: 93422,
    id: 221,
    firstName: "George",
    fullName: "George Jacob",
    middleName: " ",
    lastName: "Jacob",
    providerType: 1,
  },
  {
    clinicId: 93422,
    id: 1443,
    firstName: "Savannah ",
    fullName: "Savannah Doughty",
    middleName: " ",
    lastName: "Doughty",
    providerType: 1,
  },
];
