export const providerList = [
  {
    clinicId: 93422,
    id: 134,
    firstName: "Vinit",
    fullName: "Vinit Lal",
    middleName: " ",
    lastName: "Lal",
  
  },
  {
    clinicId: 93422,
    id: 135,
    firstName: "Randall",
    fullName: "Randall Gale",
    lastName: "Gale",
    middleName: " Glenn",
  
  },
  {
    clinicId: 93422,
    id: 136,
    firstName: "Kelsey ",
    fullName: "Kelsey Reekie",
    middleName: " ",
    lastName: "Reekie",
  
  },
  {
    clinicId: 93422,
    id: 137,
    firstName: "Mesha ",
    fullName: "Mesha Dancer",
    middleName: " ",
    lastName: "Dancer",
  
  },
  {
    clinicId: 93422,
    id: 221,
    firstName: "George",
    fullName: "George Jacob",
    middleName: " ",
    lastName: "Jacob",
  
  },
  {
    clinicId: 93422,
    id: 1443,
    firstName: "Savannah ",
    fullName: "Savannah Doughty",
    middleName: " ",
    lastName: "Doughty",
  
  },
];

export const serviceList = [
  {
    id: 1,
    name: "Office Visit",
    duration: 15,
    active: 1,
    color: -1,
    patientRequired: true,
    clinicId: 0,
  },
  {
    id: 2,
    name: "New Patient",
    duration: 30,
    active: 1,
    color: -26266,
    patientRequired: true,
    clinicId: 0,
  },
  {
    id: 3,
    name: "Personal",
    duration: 15,
    active: 1,
    color: -6684775,
    patientRequired: false,
    clinicId: 0,
  },
  {
    id: 4,
    name: "Other",
    duration: 15,
    active: 1,
    color: -5846288,
    patientRequired: false,
    clinicId: 0,
  },
  {
    id: 5,
    name: "Blocked",
    duration: 15,
    active: 1,
    color: -33664,
    patientRequired: false,
    clinicId: 0,
  },
  {
    id: 6,
    name: "FollowUp Visit",
    duration: 15,
    active: 1,
    color: -1059130,
    patientRequired: true,
    clinicId: 0,
  },
  {
    id: 7,
    name: "Consult Visit",
    duration: 15,
    active: 1,
    color: -7960954,
    patientRequired: true,
    clinicId: 0,
  },
  {
    id: 8,
    name: "Special Visit",
    duration: 15,
    active: 1,
    color: -10066177,
    patientRequired: true,
    clinicId: 0,
  },
  {
    id: 9,
    name: "Rounding",
    duration: 15,
    active: 1,
    color: -12667474,
    patientRequired: true,
    clinicId: 0,
  },
  {
    id: 6792,
    name: "New Patient",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6795,
    name: "Hospital Followup",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6791,
    name: "Established Patient",
    duration: 30,
    active: 1,
    color: 16317324,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6790,
    name: "Televisit",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6797,
    name: "Stress Echo",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6796,
    name: "Echo",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6798,
    name: "Hospital Procedure",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6800,
    name: "ABI Arterial Doppler",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6801,
    name: "Follow Up Visit",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6802,
    name: "MISC",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6803,
    name: "Stress test",
    duration: 15,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6804,
    name: "Exercise treadmill stress test",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 6799,
    name: "Carotid",
    duration: 30,
    active: 1,
    color: 16756141,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 7343,
    name: "WWE : Well Women Exam",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 7345,
    name: "ETT : exercise treadmill stress test",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 7358,
    name: "Phone : PHONE",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9418,
    name: "NEW PT : NEW PATIENT",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9419,
    name: "EST AHC : NEW TO BEATS",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9420,
    name: "ESTP : ESTABLISHED PATIENT",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9421,
    name: "SE ONLY : STRESS ECHO",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9422,
    name: "ECHO STRN : ECHO W/ STRAIN",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9423,
    name: "ESTP TELE : ESTABLISHED TELEMED",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9426,
    name: "Echocardiogram",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
  {
    id: 9427,
    name: "Office Visit",
    duration: 30,
    active: 1,
    color: 0,
    patientRequired: true,
    clinicId: 93422,
  },
];

export const FacilityList = [
  {
    id: 2694,
    locationName: "H36o test location ",
    favourite: false,
    locationAlias: "H360 test loc",
  },
  {
    id: 1087,
    locationName: "Olympia Neurological-McAlester",
    favourite: false,
    locationAlias: "Office",
  },
  {
    id: 114,
    locationName: "Texas Health Heart & Vascular Hospital Arlington",
    favourite: true,
    locationAlias: "Texas Health Heart",
  },
  {
    id: 98,
    locationName: "Heart360 Specialists Pc",
    favourite: true,
    locationAlias: "H360S Pc",
  },
];

  //status
 export const statuses = [
    // { name: "All Statuses", value: 0 },
    { name: "Visit Completed", value: 1 },
    { name: "Created", value: 2 },
    { name: "Filed", value: 3 },
    { name: "Rejected", value: 4 },
    { name: "Denied", value: 5 },
    { name: "Sec Ready", value: 6 },
    { name: "Sec Pending", value: 7 },
    { name: "Ter Ready", value: 8 },
    { name: "Ter Pending", value: 9 },
    { name: "Pat Balance", value: 10 },
    { name: "Closed", value: 11 },
    { name: "Clar Opened", value: 12 },
    { name: "Clar Closed", value: 13 },
    { name: "On Hold", value: 14 },
  ];